-- About Sections
INSERT INTO about_sections (title, content, display_order) VALUES ('Career Start and Collaborations', 'In 2015, Brapurple joined Dopester Music, where he worked alongside Hitz Magik, a sensational soul singer. This collaboration led to Dopester Music being nominated for Best Music Group by the Ghana Teens Choice Awards. Brapurple has been working autonomously as a professional musician for about two years, during which he has released three tracks.', 0);
INSERT INTO about_sections (title, content, display_order) VALUES ('Notable Projects and Achievements', 'Flees: His project titled ''Flees'' was featured on BBC Radio UK and Fresh Faves, highlighting his talent to a broader audience, particularly in the UK. ''Flees'' symbolizes ''ever readiness or looking sharp,'' and was crafted over eight months following his debut project, ''Love and Light,'' which featured Kwame Yesu. Drawn To You: He collaborated with London-based singer-songwriter Gabrielle Sey for the single ''Drawn To You,'' which has been praised for its soulful and spicy blend, showcasing Brapurple''s ability to create summer hits with a unique flavor.', 1);
INSERT INTO about_sections (title, content, display_order) VALUES ('Social and Musical Goals', 'Brapurple maintains a precise and conceited social life, keeping a closed circle of friends. His musical purpose is to elevate his hometown, Takoradi, in the Western Region of Ghana, onto the global music map.', 2);
INSERT INTO about_sections (title, content, display_order) VALUES ('Online Presence', 'Brapurple has a presence on platforms like SoundCloud, where fans can listen to his music, and Bandcamp, where he has shared his work under his stage name, further establishing his identity in the music industry.', 3);
INSERT INTO about_sections (title, content, display_order) VALUES (NULL, 'Brapurple''s work has been noted for its creativity and his ability to bring a unique, powerful feel to his music, making him a notable figure in Ghanaian music.', 4);

-- Social Links
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('appleMusic', 'https://music.apple.com/gh/artist/brapurple/1161651000', '/images/apple-music.svg', 0, true);
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('spotify', 'https://open.spotify.com/artist/3DAO5GWjPhL6J9HhtjQnw4', '/images/spotify-green.png', 1, true);
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('boomplay', 'https://www.boomplay.com/artists/7051155', '/images/boomplay.svg', 2, true);
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('tidal', 'https://tidal.com/browse/artist/45196776', '/images/tidal.svg', 3, true);
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('deezer', 'https://www.deezer.com/en/artist/11130480?deferredFl=1&utm_campaign=artist&utm_source=google&utm_medium=organic', '/images/deezer.svg', 4, true);
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('amazon', 'https://music.amazon.com/artists/B01LWRQJL3/brapurple', '/images/amazon-music.svg', 5, true);
INSERT INTO social_links (platform_name, platform_url, icon_url, display_order, is_active) VALUES ('audiomack', 'https://audiomack.com/brapurple', '/images/audiomack.svg', 6, true);

-- Releases
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('See', '/images/ARTWORK_SEE.jpeg', 'https://audiomack.com/brapurple/song/see', 'https://www.youtube.com/@Brapurple', 0, true);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Shake It To The Max (FLY) - Cover', '/images/sittm-brapurple.jpeg', 'https://audiomack.com/brapurple/song/shake-it-to-the-max-fly-cover', 'https://www.youtube.com/@Brapurple', 1, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Thanksgiving PT2 (Feat. Hitz Magik)', '/images/ARTWORK-THANKSGIVING.jpg', 'https://song.link/thanksgivingpt2', 'https://www.youtube.com/watch?v=kHYy0ut7ZkM', 2, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('No Designers (Feat. Theo XP, Lord Badu)', '/images/no_designers.jpg', 'https://song.link/nodesigners', 'https://www.youtube.com/watch?v=elyLpay20As', 3, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Drawn to You (Feat. Gabrielle Sey)', '/images/drawntoyou.jpg', 'https://song.link/drawntoyou', 'https://www.youtube.com/watch?v=RRuQoqoY8Sc', 4, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Mr Right (Feat. Sarah Angel)', '/images/mrright.jpg', 'https://song.link/mrright', 'https://www.youtube.com/watch?v=R_Flu7VPBf4', 5, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Love and Light', '/images/loveandlight.jpg', 'https://song.link/loveandlight', 'https://www.youtube.com/watch?v=gZA8dkj7IeA', 6, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Guap', '/images/guap.jpg', 'https://song.link/brapurpleGUAP', 'https://www.youtube.com/watch?v=zX7vTl4KZ5c', 7, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Flees', '/images/flees.jpg', 'https://song.link/flees', 'https://www.youtube.com/watch?v=g8PJ8k_a70Q', 8, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Lane 3', '/images/lane3.jpg', 'https://song.link/lane3', 'https://www.youtube.com/watch?v=kHYy0ut7ZkM', 9, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Wonkyemfa', '/images/wonkyemfa.jpg', 'https://song.link/wonkyemfa', 'https://www.youtube.com/watch?v=wrrGuCwkJQA', 10, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Senku', '/images/senku.jpg', 'https://song.link/senku', 'https://www.youtube.com/watch?v=hrODeU8YzC8', 11, false);
INSERT INTO releases (title, artwork_url, listen_url, watch_url, display_order, is_featured) VALUES ('Alright', '/images/alright.jpg', 'https://song.link/alrightbrapurple', 'https://www.youtube.com/watch?v=FKrB_4Gh2Ws', 12, false);
